export const loaderTokens = {
  backgroundColor: '#03040a',
  starColor: '#ffffff',
  coolStarColor: '#cfd9f5',
  dustCoolColor: '#9fb4e8',
  dustWarmColor: '#f2b56b',
  dustHotColor: '#ffd59e',
  nebulaWarmColor: '#e0702a',
  nebulaCoolColor: '#6f7fd0',
  coreColor: '#ffffff',
  coreEdgeColor: '#ffd59e',
  coreGlowColor: '#f2b56b',
  flashColor: '#fff6e8',
  shockwaveWarmColor: '#f2b56b',
  shockwaveWhiteColor: '#ffffff',
  sunHighlightColor: '#ffe2b0',
  sunLightColor: '#ffb25c',
  sunBodyColor: '#f0701d',
  sunShadowColor: '#a53a0c',
  sunInnerShadowColor: '#6e260b',
  sunHaloColor: '#e0702a',
  rayColor: '#ffb25c',
  orbitLineColor: '#ffffff',
  planetHighlightColor: '#ffffff',
  mercuryColor: '#b5b0a8',
  blueColor: '#9fb4e8',
  lilacColor: '#d58ff0',
} as const;
