export const CAMERA_FIELD_OF_VIEW = 50;

export const SYSTEM_SCREEN_FILL = 0.8;

export const PANEL_WIDTH_PIXELS = 452;

export const PANEL_SHIFT_TRANSITION_SECONDS = 0.7;

export const CAMERA_FOCUS_TRANSITION_SECONDS = 1;

export const CAMERA_FOCUS_SIDE_OFFSET_RADIANS = 0.9;
